CREATE USER C##VOTACIONES IDENTIFIED BY "12345"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER C##VOTACIONES QUOTA UNLIMITED ON USERS;
GRANT CREATE TABLE TO C##VOTACIONES;
GRANT CREATE SESSION TO C##VOTACIONES ;